animal = "   chanCHito feliz  "
print(animal.upper())
print(animal.lower())
print(animal.capitalize())
print(animal.title())
print(animal.strip())
print(animal.strip().capitalize())
print(animal.lstrip())
print(animal.rstrip())
print(animal.find("CH"))
print(animal.find("CH1"))
print(animal.replace("nCH", "j"))
print("nCH" in animal)
print("nCH" not in animal)
